server:
    port: 8081
#spring:
#    application:
#        name: config-server
#    profiles: dev
#    cloud:
#        config:
#            server:
#                git:
#                    uri: https://github.com/yuanwenjian/config-repo